### ISSUE TITLE
ionic 1 cpas data invalid

### ISSUE THREAD

**Issue by SaurabhR007** [Tazaf/ionicitude#14]
In demo app i am using 6_BrowsingPois_3_LimitingRange where in iphone i am getting error like cpas data invalid . I am using local json file of lat longs  for rendering the markers can you plese suggest wat can be the issue?

Thanks & Regards,
Saurabh

**Comment by Tazaf** [comment]
Please don't post an issue in every ionicitude-related repo.
I'm closing this one, and will try to answer your other issue [here](https://github.com/Tazaf/IonicitudeDemoApp/issues/4) within the day.
