### ISSUE TITLE
Wrong module name

### ISSUE THREAD

**Issue by GeoffSeloana** [Tazaf/ionicitude#2]
Please correct the module name "**IonicitudeModule**" to "**Ionicitude**" in the .js/min.js ionicitude files.

**Comment by Tazaf** [comment]
Hi ! Could you please elaborate as to why I should change the name ?
`Ionicitude` is the name of the service, while `IonicitudeModule` is the name of the module that encapsulates it.
Besides, this is all just naming conventions that shouldn't impact the usability of this module.

**Comment by GeoffSeloana** [comment]
Referring to the **README.md file**

**2. Registering the dependency**

Whatever installing method you choose, you'll finally have to register the module in your app's dependencies:

// In app.js or wherever you created your app's module
angular.module('app', ['ionic', '**Ionicitude**', /\* other dependencies */]);

This will give an injector error...

Error: [$injector:modulerr] Failed to instantiate module **Ionicitude** due to:
Error: [$injector:nomod] Module '**Ionicitude**' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

I had to change the naming myself but for someone who does not know anything i was just suggesting changing it yourself would help.

**Comment by Tazaf** [comment]
Oh ! I see !
Yes, this is indeed a problem with the documentation. Thanks for pointing that out :wink: 
I'll update it right away.
