### ISSUE TITLE
Ionic 2 support

### ISSUE THREAD

**Issue by FredrikHa** [Tazaf/ionicitude#4]
Hi!
I want to use Ionictude in my Ionic 2 project.
I'm pretty new to Ionic 2, and doing my best to learn it.

Do you know a way to implement Ionictude?

**Comment by Tazaf** [comment]
Hi !

For now, Ionicitude is only Ionic 1.x compliant.
And to be honest, I'm a complete newby with Angular 2 (and Ionic 2), too :wink:
Thus, I won't personnaly be able to provide an implementation of Ionicitude in Ionic 2 any time soon.

Though anyone familiar enough with the framework could easily adapt the module (it's really not rocket science).

**Comment by Tazaf** [comment]
I'm closing this issue right now, if that's ok for you :wink:
