### ISSUE TITLE
captureScreen falls to error no matter it success or fail

### ISSUE THREAD

**Issue by winsonchanwc** [Tazaf/ionicitude#6]
Hello, first of all thanks for making this wrapper, it works good

But I found that the Ionicitude.captureScreen method will falls to error no matter it successfully captured or failed. (I am using iOS), i wonder why..
Here's my code, it somehow is copied from the demo..
I want to save the screen cap to bundle path originally but it fails with this function, but even though i set it to null, i falls into the error also, but it is actually captured and saved to the device gallery

``` javascript
Ionicitude.captureScreen(false, null)
  .then(function (absoluteFilePath) {
    alert("snapshot stored at:\n" + absoluteFilePath);
    onScreenCaptured(absoluteFilePath);
  })
  .catch(function (error) {
    console.log('error');
    console.log(error);
  });
```

Thank you very much for your help

**Comment by winsonchanwc** [comment]
OK, i have opened a new project to test out... it actually works in my plain new project
maybe there's something crashed with other plugin with the callbacks...

Sorry to bother

**Comment by Tazaf** [comment]
Hi !

Don't hesitate to come back if you encounter this problem again (or any other) :wink:

**Comment by winsonchanwc** [comment]
Hello, just an update of my strange issue
I figured out what caused the problem
I have tried to modify some code in your wrapper and found out that the q immediately reject right after it called, before it can resolve.. So it can actually save a screenshot but i cannot grab the path in my code as it falls to error callback everytime..i tried to comment out the q.reject(error) and the path can invoke a successful callback in my code.

`function captureScreen(withUI, fileName) {
                ---the code of checking params----
        var q = $q.defer();
        plugin.captureScreen(function (success) {
            console.log('aaaa');
            console.log(success);
            q.resolve(success);
        }, function (error) {
            console.log('error_inQ'+error);
        //  q.reject(error);
        }, withUI, fileName);
        return q.promise;
    }`
If i didnt comment out  q.reject(error); 
The console log will always be:
error_inQnull
(some console log in action error callback for my captureScreen action)
aaaa
success - the path of image stored
And it will never falls into a successcallback in my code..
I wonder why will this happens specifically in my project..
as I open a new plain one, it works well..

**Comment by Tazaf** [comment]
You're saying that this problem only occured on one of your project, but not on another one ? That is extremly strange...
Plus, if I understand you correctly, when you decomment the line, your console logs indicate that the code inside `captureScreen()` goes through the error callback THEN the success collback ? That's even strangier...

**Comment by winsonchanwc** [comment]
Yes, as i want to debug my project in a faster way, i set up a plain project to for faster ionic build and test out things in AR as AR is only one of the module in my main project
It is very strange that the same promise code work in my plain project but not in my main project..

Maybe I will proceed to my next step first (get the dataurl from the path and do some upload stuff), then return to update with this strange issue
Thanks for your replies

**Comment by Tazaf** [comment]
I'd be glad to follow your progress and get some updates, yes.
Maybe those will reveal that there's something I could enhance in the module :wink:
