### ISSUE TITLE
Launch World from URL?

### ISSUE THREAD

**Issue by ghost** [Tazaf/ionicitude#9]
Hi @Tazaf 

I presume Ionicitude doesn't support the Wikitude-Cordova loadARchitectWorld method?

Is there a reason for this? I tried to add the method in myself (errors occurred). Wondering if you could help out? Any feedback would be good.

Thanks 

Great work by the way! 😄

**Comment by ghost** [comment]
Managed to do some hacking and got it working 😃

**Comment by Tazaf** [comment]
Hi !

Indeed, Ionicitude doesn't support launching a world through its URL. There's no specific reason why : I just didn't implement it, yet ^^

Glad you worked out something though. Do you mind sharing it here ?

**Comment by ghost** [comment]
All I did was replace the return in the getWorldUrl method with just the URL and not the edited value:

#### Before

```
function getWorldUrl(world_ref) {
     return 'www/' + settings.worldsRootFolder + '/' + world_ref + '/index.html';
}
```

#### After

```
function getWorldUrl(world_ref) {
     return world_ref;
}
```

Not ideal, but it works for what I need it to do. Thanks for the plugin!
